name: Style Chefs
favicon: null
layout_spectrum: 0.74649
typography_spectrum: 0.57179
title: Style Chefs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#ffffff'
    - '#4f4c4d'
    - '#d3d2d2'
    - '#767374'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
