name: Style Chefs
favicon: null
layout_spectrum: 0.98396
typography_spectrum: 0.31844
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#dddcdc'
    - '#8a8889'
    - '#676566'
  brandStrength: 0.7132810859475285
  lightness: 0.7013901961036026
  saturation: 0.6160856024362147
  rhythmicContrast: 0.7086079865694046
purpose: []
