typography_spectrum: 0.57179
color:
  brandColors:
    - '#231f20'
    - '#ffffff'
    - '#4f4c4d'
    - '#d3d2d2'
    - '#767374'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74649
analytics:
  google: null
  facebook: null
  twitter: null
name: Style Chefs
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Who i am | Contact | info
    id: af10cb73-f226-4fd1-8034-a9e74a971a6c
    type: content
  - name: Catering | Planning | Events
    id: 93d81886-951a-4565-9dfa-ddda5d48674f
    type: content
favicon: null
title: Style Chefs
purpose: []
