name: Style Chefs
favicon: null
layout_spectrum: 0.48331
typography_spectrum: 0.57179
title: Style Chefs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#dddcdc'
    - '#8a8889'
    - '#676566'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
