name: Style Chefs
favicon: null
layout_spectrum: 0.7936447451356798
typography_spectrum: 0.28838597889989614
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7132810859475285
  lightness: 0.7013901961036026
  saturation: 0.6160856024362147
  rhythmicContrast: 0.7086079865694046
purpose: []
